### ISSUE TITLE
Gitlab Error: Cannot find module '@semantic-release/changelog'

### ISSUE THREAD

**Issue by boojum** [semantic-release/changelog#213]
`semantic-release` fails with the ominous `Error: Cannot find module '@semantic-release/changelog'` in Gitlab CI.

Gitlab CI config:
```yml
image: node:16.14.2

stages:
  - build
  - test
  - release

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
      - node_modules
    policy: pull

setup:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    paths:
      - node_modules
  only:
    changes:
      - package-lock.json

lint:
  stage: test
  script:
    - npm run lint
  cache:
    key:
    paths:
      - cache
    policy: pull-push
  artifacts:
    paths:
      - cache

audit:
  stage: test
  script:
    - npm audit

publish:
  stage: release
  script:
    - npx semantic-release
  needs: ['lint', 'audit']
```
`semantic-release` config:
```js
module.exports = {
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/gitlab',
    '@semantic-release/git',
  ],
  release: {
    extends: '@semantic-release/gitlab-config',
    prepare: [
      '@semantic-release/changelog',
      {
        path: '@semantic-release/git',
        assets: ['package.json', 'package-lock.json', 'CHANGELOG.md'],
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
  },
}
```
Relevant packages from `devDependencies`:
```json
  "devDependencies": {
    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/gitlab": "^7.0.4",
    "@semantic-release/gitlab-config": "^10.0.0",
    "semantic-release": "^19.0.2",
  }
```
