### ISSUE TITLE
No changelog is generated during the release

### ISSUE THREAD

**Issue by budarin** [semantic-release/changelog#238]
package is private
```js
    "private": true,
```
workflow

```yaml
name: Release
on:
    push:
        branches:
            - master
            - next
            - beta
            - '*.x' # maintenance releases branches

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
```
release config
```js
module.exports = {
    plugins: [
        '@semantic-release/commit-analyzer',
        '@semantic-release/release-notes-generator',
        '@semantic-release/changelog',
        '@semantic-release/github',
        '@semantic-release/git',

    ],
};
```

release log

```
Run npx semantic-release
npm WARN exec The following package was not found and will be installed: semantic-release
[2:24:13 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.3
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[2:24:13 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[2:24:15 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.com/budarin/raketa-service-boilerplate.git
[2:24:15 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:24:15 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[2:24:15 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[2:24:15 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[2:24:15 AM] [semantic-release] › ℹ  Found git tag v1.0.18 associated with version 1.0.18 on branch master
[2:24:15 AM] [semantic-release] › ℹ  Found 2 commits since last release
[2:24:15 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:24:15 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #285 from budarin/chore--fix-code
fix: code
[2:24:15 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:24:15 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: code
META: chore--fix-code
[2:24:15 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[2:24:15 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[2:24:15 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:24:15 AM] [semantic-release] › ℹ  The next release version is 1.0.19
[2:24:15 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:24:15 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:24:1[7](https://github.com/budarin/raketa-service-boilerplate/runs/6823981884?check_suite_focus=true#step:4:8) AM] [semantic-release] › ✔  Created tag v1.0.19
[2:24:17 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[2:24:17 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/budarin/raketa-service-boilerplate/releases/tag/v1.0.19
[2:24:17 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[2:24:17 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[2:24:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #2[8](https://github.com/budarin/raketa-service-boilerplate/runs/6823981884?check_suite_focus=true#step:4:9)5: https://github.com/budarin/raketa-service-boilerplate/pull/285#issuecomment-115184[9](https://github.com/budarin/raketa-service-boilerplate/runs/6823981884?check_suite_focus=true#step:4:10)340
[2:24:23 AM] [semantic-release] [@semantic-release/github] › ℹ  Added labels [ 'released' ] to issue #285
[2:24:23 AM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/github"
[2:24:23 AM] [semantic-release] › ✔  Published release 1.0.[19](https://github.com/budarin/raketa-service-boilerplate/runs/6823981884?check_suite_focus=true#step:4:20) on default channel
```
release is created but without changelog.md
